name: Release Terminator CLI

on:
  push:
    tags:
      - 'v*'               
  workflow_dispatch:

permissions:
  contents: write              # Required to create GitHub releases

env:
  CARGO_INCREMENTAL: 0
  CARGO_NET_RETRY: 10
  RUSTUP_MAX_RETRIES: 10
  RUST_BACKTRACE: short

jobs:
  build:
    name: Build ${{ matrix.target }}
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        include:
          # ---------- Linux ----------
          - os: ubuntu-latest
            target: x86_64-unknown-linux-gnu
            archive: terminator-linux-x86_64.tar.gz
            ext: ""
          # - os: ubuntu-latest
          #   target: aarch64-unknown-linux-gnu
          #   archive: terminator-linux-aarch64.tar.gz
          #   ext: ""
          # ---------- macOS ----------
          - os: macos-13
            target: x86_64-apple-darwin
            archive: terminator-macos-x86_64.tar.gz
            ext: ""
          - os: macos-14
            target: aarch64-apple-darwin
            archive: terminator-macos-aarch64.tar.gz
            ext: ""
          # ---------- Windows ----------
          - os: windows-latest
            target: x86_64-pc-windows-msvc
            archive: terminator-windows-x86_64.zip
            ext: ".exe"
          - os: windows-11-arm
            target: aarch64-pc-windows-msvc
            archive: terminator-windows-aarch64.zip
            ext: ".exe"

    steps:
      - uses: actions/checkout@v4

      - name: Setup Rust toolchain
        uses: actions-rust-lang/setup-rust-toolchain@v1
        with:
          toolchain: stable
          target: ${{ matrix.target }}
          override: true
          cache: true

      - name: Build CLI
        run: cargo build --manifest-path terminator-cli/Cargo.toml --release --target ${{ matrix.target }}

      - name: Package (Unix)
        if: runner.os != 'Windows'
        run: |
          BIN="target/${{ matrix.target }}/release/terminator${{ matrix.ext }}"
          mkdir -p dist
          cp "$BIN" dist/
          tar -czf "${{ matrix.archive }}" -C dist "terminator${{ matrix.ext }}"

      - name: Install Linux dependencies
        if: runner.os == 'Linux'
        run: bash scripts/install_linux_deps.sh

      - name: Package (Windows)
        if: runner.os == 'Windows'
        shell: pwsh
        run: |
          $bin = "target/${{ matrix.target }}/release/terminator.exe"
          New-Item -ItemType Directory -Path dist -Force | Out-Null
          Copy-Item -Path $bin -Destination dist\terminator.exe -Force
          Push-Location dist
          Compress-Archive -Path "terminator.exe" -DestinationPath "../${{ matrix.archive }}" -Force
          Pop-Location

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: ${{ matrix.archive }}
          path: ${{ matrix.archive }}

  release:
    name: Publish GitHub Release
    needs: build
    runs-on: ubuntu-latest
    if: startsWith(github.ref, 'refs/tags/v')

    steps:
      - uses: actions/download-artifact@v4
        with:
          path: artifacts

      - name: Create GitHub Release & Upload Assets
        uses: softprops/action-gh-release@v2
        with:
          files: artifacts/**/*
